// src/vue/App.vue
<template>
    <div class="app">
        <h2>App计数器, {{ count }}</h2>
        <button @click="handleClick">+1</button>
        <button @click="decrement">-1</button>
    </div>
</template>

<script setup>
import { ref } from 'vue'


const count = ref(0)

const handleClick = () => {
    count.value++
}

const decrement = () => {
    count.value--
}
</script>

<style scoped>

</style>

// src/react/App.jsx
import React,{useState} from 'react'

function App () {
    const [count, setCount] = useState(0)

    const increment = () => {
        setCount(count + 1)
    }
    return (
        <div className="app">
            <h2>React: 计数器案例 {count}</h2>
            <button onClick={increment}>+1</button>
        </div>
    )
}

export default App
